Fix #1024, check misc API return codes
nasa/osal pull request #1030
Opened 2021-05-19 20:48 UTC by jphickey

**Describe the contribution**
Correct missing doxygen retvals and other discrepancies between test and documentation

Note, other tests were OK, but depend on support being enabled and supported by RTOS.  Script will report N/A items (due to no impl) as missing.  Confirmed OS_HeapGetInfo() is OK on RTEMS.

Fixes #1024

**Testing performed**
Run unit tests, revalidate test log against documentation

**Expected behavior changes**
No change to FSW, test/doc only

**System(s) tested on**
Ubuntu
RTEMS 4.11

**Contributor Info - All information REQUIRED for consideration of pull request**
Joseph Hickey, Vantage Systems, Inc.

2021-05-20 15:27 UTC, skliper reviewed
OS_ShellOutputToFile overloads undefined and NULL test.  Should be separate tests (one for NULL pointer, one for OS_OBJECT_ID_UNDEFINED returns OS_ERR_INVALID_ID.

2021-05-21 14:54 UTC, jphickey commented
Commit e3bd1ad4 fixes the OS_ShellOutputToFile test by moving the null pointer test to be after setup (where the file ID is valid).

This also changes the tests done before OS_API_Init() - instead of checking specifically for OS_ERROR (which is not specifically documented) this just checks that the result is not success.  Technically, calling any other API before OS_API_Init is not valid an no specific behavior is completely guaranteed here.

2021-05-24 14:22 UTC, skliper reviewed
~OS_ShellOutputToFile needs ID UNDEFINED test returns INVALID ID~
Turned into a request for change.

2021-05-24 14:23 UTC, skliper requested changes
OS_ShellOutputToFile needs ID UNDEFINED test returns INVALID ID

2021-05-26 13:46 UTC, skliper approved these changes

2021-06-02 01:51 UTC, merged