Fix377 select functional tests
nasa/osal pull request #683
Opened 2020-12-10 17:21 UTC by zanzaben

**Describe the contribution**
Fixes #377 
Added new functional tests for the the select and select multiple functions. 

**Testing performed**
Ran the new tests. 

**Expected behavior changes**
None

**System(s) tested on**
Ubuntu 20.04

**Contributor Info - All information REQUIRED for consideration of pull request**
Alex Campbell GSFC

2020-12-14 16:14 UTC, skliper requested changes
Should the client sockets get closed?

2020-12-14 16:14 UTC, skliper commented on src/tests/select-test/select-test.c
> +         UtPrintf("Buffer size too large to test Select Single OS_STREAM_STATE_WRITABLE timeout\n");
Suggest - "Unable to cause OS_STREAM_STATE_WRITEABLE timeout with large looped writes, skipping verification" and mark this as requires analysis.

2020-12-14 16:14 UTC, skliper commented on src/tests/select-test/select-test.c
> +         UtPrintf("Buffer size too large to test Select Multiple OS_STREAM_STATE_WRITABLE\n");
same comment

2020-12-14 16:14 UTC, skliper commented on src/tests/select-test/select-test.c
> +osal_id_t bin_sem_id;
Consider a global structure

2020-12-14 16:14 UTC, skliper commented on src/tests/select-test/select-test.c
> +int max_buffer_loop = 1000000;
Consider a `#define`, unless this really is a variable.

2020-12-14 16:14 UTC, skliper commented on src/tests/select-test/select-test.c
> +osal_id_t     c2_socket_id;
A quick description of the socket uses would help clarify, or maybe a more general outline of what this test does in the file description.

2020-12-14 16:14 UTC, skliper commented on src/tests/select-test/select-test.c
> +    OS_OpenCreate(&id, "/drive3/select_test.txt", OS_FILE_FLAG_CREATE | OS_FILE_FLAG_TRUNCATE, OS_READ_ONLY);
Provide some context... why "3", general concept, etc.

2020-12-16 17:27 UTC, astrogeco commented
[CCB 2020-12-16](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-December-16-2020) APPROVED

- Run `clang-format` for consistency
- Teardown closes the sockets and are used for all the tests

2020-12-16 18:24 UTC, skliper commented
@zanzaben - could you add a more descriptive commit message on the last two commits?  The current text isn't sufficient to describe the change.  Let me know if suggestions would help.

2020-12-18 14:53 UTC, merged