Fix #779, Change global vars to not be hidden by local vars.
nasa/osal pull request #794
Opened 2021-02-10 16:40 UTC by zanzaben

**Describe the contribution**
Fixes #779 
Rename global timer_id to Timer_Id

**Testing performed**
Build and run unit test

**Expected behavior changes**
No impact to behavior

**System(s) tested on**
Ubuntu 20.04

**Contributor Info - All information REQUIRED for consideration of pull request**
Alex Campbell GSFC

2021-02-12 14:17 UTC, jphickey requested changes
I'm not sure changing only the case is sufficient... I think there is a coding standard against that (i.e. having two different vars that differ only in capitalization).

Can we call the local one `local_timer_id` instead?

2021-02-12 14:20 UTC, skliper commented
Coding violation - Correct, I forgot about that one in my suggestion.

2021-02-12 18:13 UTC, jphickey approved these changes

2021-02-12 18:18 UTC, skliper approved these changes

2021-02-17 17:12 UTC, astrogeco commented
[CCB 2021-02-17](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-February-17-2021) APPROVED

2021-02-24 03:37 UTC, merged