Fix #868, Use quotes for local includes
nasa/osal pull request #892
Opened 2021-03-11 16:02 UTC by skliper

**Describe the contribution**
Fix #868 - scripted replacement for `#include <os` and `#include <OSC_` matches of `<` and `>` with `"`

**Testing performed**
Build and execute unit tests

**Expected behavior changes**
None, just coding standard

**System(s) tested on**
 - Hardware: cFS Dev Server
 - OS: Ubuntu 18.04
 - Versions: Bundle main + this commit

**Additional context**
None

**Third party code**
None

**Contributor Info - All information REQUIRED for consideration of pull request**
Jacob Hageman - NASA/GSFC

2021-03-11 21:04 UTC, zanzaben commented
Missing Some utassert, uttest and utstubs

Here is one I found 
https://github.com/nasa/osal/blob/ead5723f59ee49b36a36d6cb66c4cfe680ebbd68/src/unit-test-coverage/shared/src/os-shared-coveragetest.h#L31-L33

2021-03-12 13:40 UTC, zanzaben requested changes
See my comment about missing UT

2021-03-12 13:58 UTC, skliper commented
@zanzaben fixed, please confirm

2021-03-12 14:15 UTC, zanzaben approved these changes

2021-03-17 23:09 UTC, merged